### ISSUE TITLE
Problem with inverted touchscreen

### ISSUE THREAD

**Issue by randee01** [AndrewMascolo/TFT_Extension#1]
The portrait mode displays text and pushbuttons correctly but the pushbuttton touch areas are inverted. If the buttons are displayed side by side near the top the actual touch area is at the bottom and the bottom sides are swapped - in other words  top = bottom and left = right. The usual portrait calibration was done and works fine  as far as displaying in portrait.
The libraries are  #include <UTFT.h>
# include <UTouch.h>
# include <UTFT_Buttons.h>
# include <TFT_Extension.h>

Also  this line is shown in  of the radio buttons example as TFT_Extension myTFT(&myGLCD, &myTouch,PORTRAIT); but it won't compile unless PORTRAIT is deleted : TFT_Extension myTFT(&myGLCD, &myTouch); In addition its the same if LANDSCAPE is used instead of PORTRAIT.
Hardware is CTE70 CPLD 7" TFT and Mega2560 with shield. It works fine for an older sketch that uses landscape.

**Comment by AndrewMascolo** [comment]
Is everything else set to portrait mode too?

See reply #83 
http://forum.arduino.cc/index.php?topic=217873.75

**Comment by randee01** [comment]
Not sure. Please take a look. Its just code to test the two touch buttons.
#include <UTFT.h>
#include <UTouch.h>
#include <UTFT_Buttons.h>
#include <TFT_Extension.h>

extern uint8_t SmallFont[];
extern uint8_t BigFont[];
extern uint8_t SevenSegNumFont[];

UTFT myGLCD(CTE70CPLD,38,39,40,41);
UTouch        myTouch(6, 5, 4, 3, 2);
UTFT_Buttons  myButtons(&myGLCD, &myTouch);
TFT_Extension myTFT(&myGLCD, &myTouch); 
#define convert(x) {myTFT.ConvertRGB(x)}
#define TOUCH_ORIENTATION  PORTRAIT //portrait - from calibration file- may not be needed
int panLeftRelay = 8;  // Pan Left Touch Button 
int panRightRelay = 9;

void setup() 
{
pinMode(panLeftRelay, OUTPUT);
pinMode(panRightRelay, OUTPUT);

  // setup LCD
myGLCD.InitLCD(PORTRAIT);  //portrait
myGLCD.setFont(BigFont);  
myGLCD.clrScr();

// Setup Touch Buttons
myTouch.InitTouch(PORTRAIT);  //portrait
myTouch.setPrecision(PREC_MEDIUM);
myButtons.setTextFont(BigFont); 

  //TFT setup commands
myTFT.ExtSetup();
startup();
}

void loop()
{
getButton();
}
void startup()
{
myTFT.SetTouchButtonColors(0, ORANGE, BLUE, FILL, ROUNDED); // (ID number, Pressed Color, Released Color, FILL/NOFILL)  Page 1
myTFT.SetTouchButtonColors(1, ORANGE, GREEN, FILL, ROUNDED); // ID number, Pressed Color, Released Color, FILL/NOFILL)   Page 2

myTFT.SetTouchButtonText(0, "Page 1", Big, BLUE); // (Text, Font, Color)
myTFT.SetTouchButtonText(1, "Page 2", Big, BLUE); // (Text, Font, Color)
 }

void getButton()
{

if (myTFT.TouchButton_Draw(20,20,180,60,0)) //Draw Pan Left Button, ID = 0 
{
 digitalWrite(panLeftRelay, HIGH);  //High when button is pressed
 myGLCD.print("Button 0", 60, 200);

  }
  else
  {
    digitalWrite(panLeftRelay, LOW);   //  Low when button is not pressed
  }

  if (myTFT.TouchButton_Draw(220,20,380,60,1)) //Draw Pan Right Button, ID = 1

  {
    digitalWrite(panRightRelay, HIGH);  // High when button is pressed
    myGLCD.print("Button 1", 260, 200);
  }
else
  {
    digitalWrite(panRightRelay, LOW); 

  }
}

**Comment by randee01** [comment]
#include <UTFT.h>
#include <UTouch.h>
#include <UTFT_Buttons.h>
#include <TFT_Extension.h>

extern uint8_t SmallFont[];
extern uint8_t BigFont[];
extern uint8_t SevenSegNumFont[];

UTFT myGLCD(CTE70CPLD,38,39,40,41);
UTouch        myTouch(6, 5, 4, 3, 2);
UTFT_Buttons  myButtons(&myGLCD, &myTouch);
TFT_Extension myTFT(&myGLCD, &myTouch); 
#define convert(x) {myTFT.ConvertRGB(x)}
#define TOUCH_ORIENTATION  0 //portrait - from calibration file
int panLeftRelay = 8;  // Pan Left Touch Button 
int panRightRelay = 9;

void setup() 
{
pinMode(panLeftRelay, OUTPUT);
pinMode(panRightRelay, OUTPUT);

  // setup LCD
myGLCD.InitLCD(0);  //portrait
myGLCD.setFont(BigFont);  
myGLCD.clrScr();

// Setup Touch Buttons
myTouch.InitTouch(0);  //portrait
myTouch.setPrecision(PREC_MEDIUM);
myButtons.setTextFont(BigFont); 
 
  //TFT setup commands
myTFT.ExtSetup();
startup();
}

void loop()
{
getButton();
}
void startup()
{
myTFT.SetTouchButtonColors(0, ORANGE, BLUE, FILL, ROUNDED); // (ID number, Pressed Color, Released Color, FILL/NOFILL)  Page 1
myTFT.SetTouchButtonColors(1, ORANGE, GREEN, FILL, ROUNDED); // ID number, Pressed Color, Released Color, FILL/NOFILL)   Page 2

myTFT.SetTouchButtonText(0, "Page 1", Big, BLUE); // (Text, Font, Color)
myTFT.SetTouchButtonText(1, "Page 2", Big, BLUE); // (Text, Font, Color)
 }

void getButton()
{
  
if (myTFT.TouchButton_Draw(20,20,180,60,0)) //Draw Pan Left Button, ID = 0 
{
 digitalWrite(panLeftRelay, HIGH);  //High when button is pressed
 myGLCD.print("Button 0", 60, 200);
  
  }
  else
  {
    digitalWrite(panLeftRelay, LOW);   //  Low when button is not pressed
  }
 
  if (myTFT.TouchButton_Draw(220,20,380,60,1)) //Draw Pan Right Button, ID = 1
  
  {
    digitalWrite(panRightRelay, HIGH);  // High when button is pressed
    myGLCD.print("Button 1", 260, 200);
  }
else
  {
    digitalWrite(panRightRelay, LOW); 

  }
}

**Comment by randee01** [comment]
Just checked your link. I see - TFT_Extension myTFT(&myGLCD, &myTouch);  doesn't need portrait or landscape now. The sketch till doesn't work when everything (that I know of) is set to PORTRAIT. But if UTouchCD.h is set to landscape values instead of portrait calibration values the buttons display correctly but the touch operation is inverted. If  the sketch is in PORTRAIT as before is in portrait the touch  buttons still display fine but their is no touch operation anywhere on the display.
Thanks,
Randy

**Comment by AndrewMascolo** [comment]
I have had a similar case before where someone was having issues with a 5" display. I'll take another look tonight when I get home.

**Comment by randee01** [comment]
This fixed it!!  Its probably not the right way to do it but it works so far! Swapped X and Y values for the LANDSCAPE values in UTouchCD.h. Lines 20,21,22.

#define CAL_X 0x00568F45UL //landscape  SWAPPED WITH Y
#define CAL_Y 0x03E44044UL //landscape  SWAPPED WITH X
#define CAL_S 0x8031F1DFUL //landscape

**Comment by randee01** [comment]
Hi Andrew,Swapping the X and Y values for the LANDSCAPE values in UTouchCD.h. Lines 20,21,22.fixed it. Now the touch screen buttons work fine so far.  Everything my sketch is still in portrait - no changes.  Wonder if he found the problem for his 5" display.#define CAL_X 0x00568F45UL //landscape SWAPPED WITH Y
#define CAL_Y 0x03E44044UL //landscape SWAPPED WITH X
#define CAL_S 0x8031F1DFUL //landscape
Randy      From: AndrewMascolo notifications@github.com
 To: AndrewMascolo/TFT_Extension TFT_Extension@noreply.github.com 
Cc: randee01 randee01@yahoo.com 
 Sent: Friday, May 1, 2015 11:10 AM
 Subject: Re: [TFT_Extension] Problem with inverted touchscreen (#1)

I have had a similar case before where someone was having issues with a 5" display. I'll take another look tonight when I get home.
