### ISSUE TITLE
Missing TRON.h font

### ISSUE THREAD

**Issue by Rinksrides2013** [AndrewMascolo/TFT_Extension#2]
Tried the connect four, 1.0.6 reports:

Arduino: 1.0.6 (Windows 7), Board: "Arduino Mega 2560 or Mega ADK"
TFT_EXT\TFT_Extension.cpp.o: In function `TFT_Extension::TextButton(char*, unsigned char, int, int, int, int, unsigned char, unsigned char, unsigned char)':
C:\Users\Michael\Desktop\arduino-1.0.6-windows\arduino-1.0.6\libraries\TFT_EXT/TFT_Extension.cpp:531: undefined reference to`TRONFont'
C:\Users\Michael\Desktop\arduino-1.0.6-windows\arduino-1.0.6\libraries\TFT_EXT/TFT_Extension.cpp:531: undefined reference to `TRONFont'

Could you upload this TRON font?

**Comment by AndrewMascolo** [comment]
Uploaded.

**Comment by Rinksrides2013** [comment]
Thank you. Nice demos.
